adapter: qlora
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: /app/output/adapter

sequence_len: 16384 # huge documents
sample_packing: false
pad_to_sequence_len: false

# default: optimized for multiple 24GB VRAM cards
micro_batch_size: 1
gradient_accumulation_steps: 8

num_epochs: 3
optimizer: paged_adamw_8bit # reduces VRAM usage
lr_scheduler: cosine
learning_rate: 0.0002

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

flash_attention: true