base_model: unsloth/Mixtral-8x7B-Instruct-v0.1-bnb-4bit
load_in_4bit: true

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: false

logging_steps: 1
warmup_steps: 10
evals_per_epoch: 0
saves_per_epoch: 1
weight_decay: 0.0