inference_model: casperhansen/mixtral-instruct-awq # custom field, removed before training

base_model: unsloth/Mixtral-8x7B-Instruct-v0.1-bnb-4bit
load_in_4bit: true

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: false

logging_steps: 1
warmup_ratio: 0.1
evals_per_epoch: 0
saves_per_epoch: 1
weight_decay: 0.0

datasets:
  - path: data/train/dataset.jsonl
    type: chat_template
    chat_template_jinja: "{{ bos_token }}{% for message in messages %}{% if message['role'] == 'system' %}{{ '[INST] ' + message['content'] + '\n\n' }}{% elif message['role'] == 'user' %}{{ message['content'] + ' [/INST] ' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token }}{% endif %}{% endfor %}"
    field_messages: messages
    message_property_mappings:
      role: role
      content: content