base_model: unsloth/mixtral-8x7b-v0.1-bnb-4bit
load_in_4bit: true

adapter: qlora
peft_use_dora: true

datasets:
  - path: data/axolotl_dataset.jsonl
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    chat_template: mistral

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: /app/output

sequence_len: 1024
sample_packing: true
pad_to_sequence_len: true

micro_batch_size: 1
gradient_accumulation_steps: 8 # optimized for multiple 24GB VRAM cards
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

logging_steps: 1
flash_attention: true

warmup_steps: 10
evals_per_epoch: 0
saves_per_epoch: 1
weight_decay: 0.0

deepspeed: config/zero3.json