[project]
name = "vllm-moe-evaluation"
version = "0.1.0"
description = "vLLM Evaluation Pipeline"
readme = "../README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "pytest>=8.0.0",
    "textstat>=0.7.13",
    "awscli",
    "boto3",
    "transformers==4.48.2",
    "vllm==0.7.3",
    "mistral_common>=1.11.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
