name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect changes in docker image dependencies
    runs-on: ubuntu-latest
    outputs:
      docker_files: ${{ steps.filter.outputs.docker_files }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docker_files:
              - 'runner/**'
              - 'Dockerfile'
              - 'pyproject.toml'
              - 'uv.lock'

  build-docker-image:
    name: Build and push Docker image
    needs: detect-changes
    # Run ONLY IF docker image changed or if the user manually triggered the workflow
    if: needs.detect-changes.outputs.docker_files != '' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Free up GitHub runner disk space # otherwise the huge docker build fails
        run: |
          echo "Freeing up disk space"
          docker system prune -af
          sudo time rm -rf /usr/share/dotnet
          sudo time rm -rf /usr/local/lib/android
          sudo time rm -rf /opt/ghc
          sudo time rm -rf /opt/hostedtoolcache
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Show Image Size
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}"
          echo "Uncompressed Local Image Size:"
          docker images $IMAGE_NAME
      - name: Environment Smoke Test
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}"
          echo "Running dependency sanity check inside the container..."
          
          # -v dynamically mounts the GitHub runner's workspace into the container
          # -w sets the working directory so Python can find the tests folder
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            --entrypoint python \
            $IMAGE_NAME tests/container_smoke_test.py
      - name: Push Docker image to GHCR
        run: |
          for tag in ${{ steps.meta.outputs.tags }}; do
            echo "Pushing $tag..."
            docker push $tag
          done          