name: Detect Docker Changes

on:
  workflow_call:
    outputs:
      docker_changed:
        description: "True if Docker-related files changed"
        value: ${{ jobs.detect.outputs.docker_files }}

jobs:
  detect:
    name: Detect changes in docker image dependencies
    runs-on: ubuntu-latest
    outputs:
      docker_files: ${{ steps.filter.outputs.docker_files }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker_files:
              - 'runner/**'
              - 'Dockerfile'
              - 'pyproject.toml'
              - 'uv.lock'