name: Continuous Integration

on:
  pull_request:

jobs:
  check-dependabot:
    name: Check Dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate dependabot.yml
        uses: marocchino/validate-dependabot@v3
        with:
          path: .github/dependabot.yml

  validate-data:
    name: Check if dataset was prepared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: iterative/setup-dvc@v3
      - name: Pull dataset from DVC
        run: dvc pull
      - name: Check if final dataset is up-to-date with raw data
        run: dvc status; dvc status -q # First for visibility, second to fail if invalid

  test-python:
    name: Test Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Run Pytest
        run: uv run pytest tests/

